import type { EngineV2Input, EngineV2Position, EngineV2Side } from "../types";

export type V2StateAuthoritySource = "v2_state_authority_from_bridge";

export type V2StateAuthority = Readonly<{
    symbol: EngineV2Input["symbol"];
    now: number;
    currentPositions: EngineV2Position[];
    symbolPositions: EngineV2Position[];
    longPosition: EngineV2Position | null;
    shortPosition: EngineV2Position | null;
    hasLongPosition: boolean;
    hasShortPosition: boolean;
    longStage: number;
    shortStage: number;
    sameSidePosition: EngineV2Position | null;
    oppositeSidePosition: EngineV2Position | null;
    hasSameSidePosition: boolean;
    hasOppositeSidePosition: boolean;
    currentStage: number;
    positionStateReady: boolean;
    marketSnapshotReady: boolean;
    v2InputReady: boolean;
    serverTradeEnabled: boolean;
    closeOnlyMode: boolean;
    killSwitch: boolean;
    reconcileSafeMode: boolean;
    riskMode: string | null;
    dailyLossGuardTriggered: boolean;
    freshTickBarrierActive: boolean;
    freshTickExecutionBlocked: boolean;
    freshTickCompletedCycles: number;
    freshTickRequiredCycles: number;
    paperExecutionReady: boolean;
    signedExecutionReady: boolean;
    okxAuthMode: "disabled" | "demo" | "live";
    okxAuthReady: boolean;
    okxExchangeAuthOptIn: boolean;
    okxLiveEnabled: boolean;
    okxDemoEnabled: boolean;
    okxApiKeyPresent: boolean;
    okxApiSecretPresent: boolean;
    okxPassphrasePresent: boolean;
    okxSimulatedTradingHeaderEnabled: boolean;
    liveMaxOrderNotionalUsdt: number;
    directionalShockState: "UP" | "DOWN" | "NONE" | "UNKNOWN";
    rawDirectionalShockState?: "UP" | "DOWN" | "NONE" | "UNKNOWN";
    stabilizedDirectionalShockState?: "UP" | "DOWN" | "NONE" | "UNKNOWN";
    rawShockMovePct?: number;
    requiredShockMovePct?: number;
    shockEmergencyBypass?: boolean;
    crashState: string;
    pumpState: string;
    longAllow: boolean;
    shortAllow: boolean;
    accountEquityKrw: number;
    maxUsableMarginKrw: number;
    exposureNotionalCapKrw: number;
    symbolExposureNotionalCapKrw: number;
    ledgerExposureNotionalKrw: number;
    symbolLedgerExposureNotionalKrw: number;
    lossStreaks: Record<string, number>;
    entryQualityProfiles: EngineV2Input["state"]["entryQualityProfiles"];
    stateAuthoritySource: V2StateAuthoritySource;
    /** Sole open / OKX-resolved management side for the held position (not market candidate). */
    heldPositionSide: EngineV2Side;
    /** Alias for heldPositionSide — ledger/OKX management identity. */
    managementSide: EngineV2Side;
    /** Entry/routing candidate from signal/emaGap/shock (inferIntentSide). */
    candidateIntentSide: EngineV2Side;
    /** @deprecated Use candidateIntentSide — kept for existing consumers. */
    inferredIntentSide: EngineV2Side;
    /** Diagnostic: held side differs from candidate intent (does not redefine held identity). */
    hasOppositeToCandidate: boolean;
    liveBalanceReady?: boolean;
    accountEquityUsdt?: number;
    availableBalanceUsdt?: number;
    okxActualPositionsReady?: boolean;
    actualAccountNotionalUsdtReady?: boolean;
    okxActualPositions?: Array<{ symbol: string; sizeUsd?: number; notionalUsd?: number; side: string }>;
    okxPendingOrdersReady?: boolean;
    okxPendingOrdersNotionalUsdt?: number;
    okxPendingSymbolNotionalUsdt?: number;
    hasSymbolPendingEntry?: boolean;
    hasUnknownPendingNotional?: boolean;
    balanceFetchedAt?: number;
    positionsFetchedAt?: number;
    pendingOrdersFetchedAt?: number;
    lastLossReentryState?: import("./loss-reentry-gate").LastLossReentryState | null;
    hasOperatorPendingOrders?: boolean;
    manualTakeoverActive?: boolean;
}>;
